# Generated by Django 5.0.6 on 2024-08-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeweller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jeweler',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='jewellercategory',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='jewellerproduct',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
