# Generated by Django 5.0.3 on 2025-10-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MethodStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='Step number (1, 2, 3, etc.)')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional detailed description', null=True)),
                ('icon', models.ImageField(help_text='Step icon image', upload_to='method_icons/')),
                ('image_alt', models.CharField(blank=True, help_text='Alt text for accessibility', max_length=200, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Method Step',
                'verbose_name_plural': 'Method Steps',
                'ordering': ['order', 'number'],
            },
        ),
    ]
