# Generated by Django 5.0.3 on 2025-10-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_methodstep'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='methodstep',
            options={'ordering': ['step_number']},
        ),
        migrations.RemoveField(
            model_name='methodstep',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='methodstep',
            name='image_alt',
        ),
        migrations.RemoveField(
            model_name='methodstep',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='methodstep',
            name='number',
        ),
        migrations.RemoveField(
            model_name='methodstep',
            name='order',
        ),
        migrations.AddField(
            model_name='methodstep',
            name='image',
            field=models.ImageField(default=1, upload_to='method_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='methodstep',
            name='step_number',
            field=models.IntegerField(choices=[(1, 'Step 1'), (2, 'Step 2'), (3, 'Step 3'), (4, 'Step 4'), (5, 'Step 5')], default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='methodstep',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
