# Generated by Django 5.0.3 on 2025-10-09 10:47

import webpfield.fields
import webpfield.webp_storage
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_methodstep_options_remove_methodstep_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=webpfield.fields.WebPField(storage=webpfield.webp_storage.WebPStorage(), upload_to='blog_images/'),
        ),
        migrations.AlterField(
            model_name='ceo',
            name='image',
            field=webpfield.fields.WebPField(blank=True, null=True, storage=webpfield.webp_storage.WebPStorage(), upload_to='team_images/'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=webpfield.fields.WebPField(storage=webpfield.webp_storage.WebPStorage(), upload_to='gallery/large/'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='logo',
            field=webpfield.fields.WebPField(storage=webpfield.webp_storage.WebPStorage(), upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='logosecond',
            name='logo',
            field=webpfield.fields.WebPField(storage=webpfield.webp_storage.WebPStorage(), upload_to='logos_second/'),
        ),
        migrations.AlterField(
            model_name='logothird',
            name='logo',
            field=webpfield.fields.WebPField(storage=webpfield.webp_storage.WebPStorage(), upload_to='logos_third/'),
        ),
        migrations.AlterField(
            model_name='methodstep',
            name='image',
            field=webpfield.fields.WebPField(storage=webpfield.webp_storage.WebPStorage(), upload_to='method_images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=webpfield.fields.WebPField(storage=webpfield.webp_storage.WebPStorage(), upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=webpfield.fields.WebPField(blank=True, null=True, storage=webpfield.webp_storage.WebPStorage(), upload_to='service_icons/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=webpfield.fields.WebPField(storage=webpfield.webp_storage.WebPStorage(), upload_to='service_images/'),
        ),
        migrations.AlterField(
            model_name='storyimage',
            name='image',
            field=webpfield.fields.WebPField(storage=webpfield.webp_storage.WebPStorage(), upload_to='stories/images/'),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='icon',
            field=webpfield.fields.WebPField(storage=webpfield.webp_storage.WebPStorage(), upload_to='icons/'),
        ),
        migrations.AlterField(
            model_name='teamimage',
            name='image',
            field=webpfield.fields.WebPField(storage=webpfield.webp_storage.WebPStorage(), upload_to='team_image/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=webpfield.fields.WebPField(blank=True, null=True, storage=webpfield.webp_storage.WebPStorage(), upload_to='team_images/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='logo',
            field=webpfield.fields.WebPField(storage=webpfield.webp_storage.WebPStorage(), upload_to='testimonials/logos/'),
        ),
        migrations.AlterField(
            model_name='workscreenshot',
            name='image',
            field=webpfield.fields.WebPField(storage=webpfield.webp_storage.WebPStorage(), upload_to='screenshots/'),
        ),
    ]
