# Generated by Django 5.0.3 on 2025-10-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_blog_image_alter_ceo_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navbaritem',
            options={'ordering': ['order', 'label']},
        ),
        migrations.AddField(
            model_name='navbaritem',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order (lower numbers show first)'),
        ),
    ]
