# Generated by Django 5.0.6 on 2024-08-02 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jeweller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='jeweller_images/')),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100)),
                ('contact_person_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('website_or_instagram', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('rating', models.IntegerField(default=5)),
                ('review', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('kids', 'Kids'), ('newborn', 'New Born')], max_length=10)),
                ('gold_purity', models.CharField(choices=[('gold24CT', '24 CT'), ('gold22CT', '22 CT'), ('gold18CT', '18 CT'), ('gold14CT', '14 CT'), ('gold95CT', '95.00 CT')], max_length=10, null=True)),
                ('metal_color', models.CharField(choices=[('white', 'White'), ('rose', 'Rose'), ('yellow', 'Yellow'), ('dualTone', 'Dual Tone')], max_length=10, null=True)),
                ('name', models.CharField(max_length=255)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=10)),
                ('price_range', models.CharField(max_length=50, null=True)),
                ('product_video', models.URLField(blank=True, null=True)),
                ('product_code', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
                ('jeweller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.jeweller')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='desc', to='main.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stone_type', models.CharField(choices=[('none', 'No stone available'), ('diamond', 'Diamond'), ('ruby', 'Ruby'), ('sapphire', 'Sapphire'), ('emerald', 'Emerald')], default='none', max_length=50)),
                ('metal_purity_details', models.CharField(choices=[('gold24CT', '24 CT'), ('gold22CT', '22 CT'), ('gold18CT', '18 CT'), ('gold14CT', '14 CT'), ('gold95CT', '95.00 CT')], default='22ct', max_length=50)),
                ('wearing_style', models.CharField(default='Daily Wear', max_length=50)),
                ('metal_color', models.CharField(choices=[('white', 'White'), ('rose', 'Rose'), ('yellow', 'Yellow'), ('dualTone', 'Dual Tone')], default='yellow', max_length=10)),
                ('occasion', models.CharField(choices=[('daily_wear', 'Daily Wear'), ('wedding', 'Wedding'), ('party', 'Party'), ('casual', 'Casual'), ('formal', 'Formal')], default='daily_wear', max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
                ('jeweller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='main.jeweller')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='main.product')),
            ],
        ),
    ]
