# Generated by Django 5.0.6 on 2024-08-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_category_slug_jeweller_slug_product_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='downloadable_photo',
            field=models.FileField(blank=True, null=True, upload_to='downloadable_photos/'),
        ),
    ]
